def verify_weather(region, season):
    actual_weather = []

    # 



weather = [
    "agradável"
    "ameno e úmido"
    "brisa quente"
    "chuva"
    "chuva de granizo!"
    "chuva e neblina!"
    "chuva e vento"
    "chuva forte!"
    "chuva fria!"
    "chuva forte"
    "chuva torrencial!"
    "claro e ameno"
    "claro e com vento"
    "ensolarado e ameno"
    "ensolarado e claro"
    "frio e úmido"
    "frio e claro"
    "frio e seco"
    "garoa"
    "garoa leve"
    "garoa morna"
    "geada"
    "gelado e nublado"
    "limpo e com vento"
    "neblina fria"
    "nevando forte!"
    "nevando leve"
    "nevasca!!"
    "nevoa densa!"
    "nublado e morno"
    "nublado e ameno"
    "nublado e com vento"
    "nublado e congelante"
    "nublado e frio"
    "nublado e úmido"
    "ondas de calor!!"
    "parcialmente nublado e ameno"
    "quente e abafado!"
    "quente e com vento!"
    "quente e úmido"
    "quente e seco!"
    "quente nublado"
    "sereno"
    "tempestade!"
    "tempestade!"
    "tempo limpo e ameno"
    "vento e neve!"
    "vento forte!"
    "vento frio"
    "ventos esporádicos!"
    "ventos frios"
    "sereno morno"
]
